# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Check PR Title

on:
  pull_request:
    # types: [opened]
    branches: [main]
  # pull_request_review:
  #   types: [submitted]

jobs:
  build:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Check PR
        run: node scripts/check-pr-title
