name: Master Release

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      name:
        type: choice
        required: true
        description: Which environment to deploy to?
        options:
          - staging
          - production
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
