name: Trigger Master Release

on:
  workflow_dispatch:
    inputs:
      hf-env:
        type: choice
        required: true
        description: Which environment to deploy to?
        options:
          - staging
          - production
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  release_staging:
    if: ${{ github.event.inputs.hf-env == 'staging' }}
    runs-on: ubuntu-latest

    steps:
      - name: Release to staging
        run: echo STAG "${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.hf-env }}"

  release_production:
    if: ${{ github.event.inputs.hf-env == 'production' }}
    runs-on: ubuntu-latest

    steps:
      - name: Release to production
        run: echo PROD "${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.hf-env }}"
